In [4]:
import numpy as np

a=np.arange(8)
b=np.arange(8)
print(a)

tmp1=np.reshape(a,[2,len(a)//2],order="F")
print(tmp1)
c=np.concatenate([a+b,b])
print(c)


[0 1 2 3 4 5 6 7]
[[0 2 4 6]
 [1 3 5 7]]
[ 0  2  4  6  8 10 12 14  0  1  2  3  4  5  6  7]
